name: Build wutong Exclusive KMI

on:
  workflow_dispatch:
  push:
    branches: [ "ci" ]
    paths:
      - '.github/workflows/wutong-exclusive-kmi.yml'
      - '.github/workflows/ddk-lkm.yml'
      - 'kernel/**'

jobs:
  build-exclusive-kmi:
    strategy:
      fail-fast: false
      matrix:
        kmi:
          - android12-5.10
          - android13-5.10
          - android13-5.15
          - android14-5.15
          - android14-6.1
          - android15-6.6
          - android16-6.12
          - android17-6.18
    uses: ./.github/workflows/ddk-lkm.yml
    with:
      kmi: ${{ matrix.kmi }}
      manager_package: com.jinfuwei.wutong
